import { KeyValue } from './key-value.type'

export const PlacesTypes: KeyValue[] = [
  { key: 'accounting', value: 'contabilidade' },
  { key: 'airport', value: 'aeroporto' },
  { key: 'amusement_park', value: 'parque de diversões' },
  { key: 'aquarium', value: 'aquário' },
  { key: 'art_gallery', value: 'galeria de arte' },
  { key: 'atm', value: 'caixa eletrônico' },
  { key: 'bakery', value: 'padaria' },
  { key: 'bank', value: 'banco' },
  { key: 'bar', value: 'bar' },
  { key: 'beauty_salon', value: 'salão de beleza' },
  { key: 'bicycle_store', value: 'loja de bicicletas' },
  { key: 'book_store', value: 'livraria' },
  { key: 'bowling_alley', value: 'boliche' },
  { key: 'bus_station', value: 'estação de ônibus' },
  { key: 'cafe', value: 'café' },
  { key: 'campground', value: 'camping' },
  { key: 'car_dealer', value: 'concessionária' },
  { key: 'car_rental', value: 'aluguel de carros' },
  { key: 'car_repair', value: 'oficina de carros' },
  { key: 'car_wash', value: 'lava-rápido' },
  { key: 'casino', value: 'cassino' },
  { key: 'cemetery', value: 'cemitério' },
  { key: 'church', value: 'igreja' },
  { key: 'city_hall', value: 'prefeitura' },
  { key: 'clothing_store', value: 'loja de roupas' },
  { key: 'convenience_store', value: 'loja de conveniência' },
  { key: 'courthouse', value: 'tribunal' },
  { key: 'dentist', value: 'dentista' },
  { key: 'department_store', value: 'loja de departamentos' },
  { key: 'doctor', value: 'médico' },
  { key: 'drugstore', value: 'farmácia' },
  { key: 'electrician', value: 'eletricista' },
  { key: 'electronics_store', value: 'loja de eletrônicos' },
  { key: 'embassy', value: 'embaixada' },
  { key: 'fire_station', value: 'corpo de bombeiros' },
  { key: 'florist', value: 'floricultura' },
  { key: 'funeral_home', value: 'funerária' },
  { key: 'furniture_store', value: 'loja de móveis' },
  { key: 'gas_station', value: 'posto de gasolina' },
  { key: 'gym', value: 'academia' },
  { key: 'hair_care', value: 'cuidados com o cabelo' },
  { key: 'hardware_store', value: 'loja de ferragens' },
  { key: 'hindu_temple', value: 'templo hindu' },
  { key: 'home_goods_store', value: 'loja de artigos para casa' },
  { key: 'hospital', value: 'hospital' },
  { key: 'insurance_agency', value: 'agência de seguros' },
  { key: 'jewelry_store', value: 'joalheria' },
  { key: 'laundry', value: 'lavanderia' },
  { key: 'lawyer', value: 'advogado' },
  { key: 'library', value: 'biblioteca' },
  { key: 'light_rail_station', value: 'estação de trem leve' },
  { key: 'liquor_store', value: 'loja de bebidas' },
  { key: 'local_government_office', value: 'escritório do governo local' },
  { key: 'locksmith', value: 'chaveiro' },
  { key: 'lodging', value: 'hospedagem' },
  { key: 'meal_delivery', value: 'entrega de refeições' },
  { key: 'meal_takeaway', value: 'comida para viagem' },
  { key: 'mosque', value: 'mesquita' },
  { key: 'movie_rental', value: 'locação de filmes' },
  { key: 'movie_theater', value: 'cinema' },
  { key: 'moving_company', value: 'empresa de mudanças' },
  { key: 'museum', value: 'museu' },
  { key: 'night_club', value: 'boate' },
  { key: 'painter', value: 'pintor' },
  { key: 'park', value: 'parque' },
  { key: 'parking', value: 'estacionamento' },
  { key: 'pet_store', value: 'pet shop' },
  { key: 'pharmacy', value: 'farmácia' },
  { key: 'physiotherapist', value: 'fisioterapeuta' },
  { key: 'plumber', value: 'encanador' },
  { key: 'police', value: 'polícia' },
  { key: 'post_office', value: 'correio' },
  { key: 'primary_school', value: 'escola primária' },
  { key: 'real_estate_agency', value: 'imobiliária' },
  { key: 'restaurant', value: 'restaurante' },
  { key: 'roofing_contractor', value: 'empreiteiro de telhados' },
  { key: 'rv_park', value: 'parque para RV (Veículos Recreativos)' },
  { key: 'school', value: 'escola' },
  { key: 'secondary_school', value: 'escola secundária' },
  { key: 'shoe_store', value: 'loja de sapatos' },
  { key: 'shopping_mall', value: 'shopping center' },
  { key: 'spa', value: 'spa' },
  { key: 'stadium', value: 'estádio' },
  { key: 'storage', value: 'armazenamento' },
  { key: 'store', value: 'loja' },
  { key: 'subway_station', value: 'estação de metrô' },
  { key: 'supermarket', value: 'supermercado' },
  { key: 'synagogue', value: 'sinagoga' },
  { key: 'taxi_stand', value: 'ponto de táxi' },
  { key: 'tourist_attraction', value: 'atração turística' },
  { key: 'train_station', value: 'estação de trem' },
  { key: 'transit_station', value: 'estação de trânsito' },
  { key: 'travel_agency', value: 'agência de viagens' },
  { key: 'university', value: 'universidade' },
  { key: 'veterinary_care', value: 'cuidado veterinário' },
  { key: 'zoo', value: 'zoológico' },
]
